/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { EditorSectionActions } from "./enums/editor-section-actions";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SideBar {
    }
    interface SlothEditor {
        "sections": string;
        "title": string;
    }
    interface SlothEditorSection {
        "contentOriginalLanguage": string;
        "contentTargetLanguage": string;
        "sectionId": string;
        "type": string;
    }
    interface SlothThumbnailChooser {
    }
}
export interface SlothEditorSectionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSlothEditorSectionElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSideBarElement extends Components.SideBar, HTMLStencilElement {
    }
    var HTMLSideBarElement: {
        prototype: HTMLSideBarElement;
        new (): HTMLSideBarElement;
    };
    interface HTMLSlothEditorElement extends Components.SlothEditor, HTMLStencilElement {
    }
    var HTMLSlothEditorElement: {
        prototype: HTMLSlothEditorElement;
        new (): HTMLSlothEditorElement;
    };
    interface HTMLSlothEditorSectionElement extends Components.SlothEditorSection, HTMLStencilElement {
    }
    var HTMLSlothEditorSectionElement: {
        prototype: HTMLSlothEditorSectionElement;
        new (): HTMLSlothEditorSectionElement;
    };
    interface HTMLSlothThumbnailChooserElement extends Components.SlothThumbnailChooser, HTMLStencilElement {
    }
    var HTMLSlothThumbnailChooserElement: {
        prototype: HTMLSlothThumbnailChooserElement;
        new (): HTMLSlothThumbnailChooserElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "side-bar": HTMLSideBarElement;
        "sloth-editor": HTMLSlothEditorElement;
        "sloth-editor-section": HTMLSlothEditorSectionElement;
        "sloth-thumbnail-chooser": HTMLSlothThumbnailChooserElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SideBar {
    }
    interface SlothEditor {
        "sections"?: string;
        "title"?: string;
    }
    interface SlothEditorSection {
        "contentOriginalLanguage"?: string;
        "contentTargetLanguage"?: string;
        "onAction"?: (event: SlothEditorSectionCustomEvent<{ action: EditorSectionActions, id: string }>) => void;
        "sectionId"?: string;
        "type"?: string;
    }
    interface SlothThumbnailChooser {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "side-bar": SideBar;
        "sloth-editor": SlothEditor;
        "sloth-editor-section": SlothEditorSection;
        "sloth-thumbnail-chooser": SlothThumbnailChooser;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "side-bar": LocalJSX.SideBar & JSXBase.HTMLAttributes<HTMLSideBarElement>;
            "sloth-editor": LocalJSX.SlothEditor & JSXBase.HTMLAttributes<HTMLSlothEditorElement>;
            "sloth-editor-section": LocalJSX.SlothEditorSection & JSXBase.HTMLAttributes<HTMLSlothEditorSectionElement>;
            "sloth-thumbnail-chooser": LocalJSX.SlothThumbnailChooser & JSXBase.HTMLAttributes<HTMLSlothThumbnailChooserElement>;
        }
    }
}
