[package]
name = "pgs_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "pgs_common"

[dependencies]
tokio-postgres = "0.7.10"
serde = { version = "1.0.197", features = ["derive"] }
