[package]
name = "interpreters"
edition.workspace = true
version.workspace = true

[dependencies]
unicode-segmentation = "1.12.0"
regex = "1.11.1"
serde = { workspace = true }

[dependencies.html-escape]
version = "*"
default-features = false
