use crate::models::post_status::PostStatus;

pub struct SinglePost {
    pub title: String,
    pub uuid: String,
    pub original_lang_entry_uuid: String,
    pub lang: String,
    pub slug: String,
    pub post_type: String,
    pub author: String,
    pub content: String,
    pub excerpt: String,
    pub css: String,
    pub use_theme_css: bool,
    pub js: String,
    pub use_theme_js: bool,
    pub thumbnail: String,
    pub publish_date: f64,
    pub update_date: f64,
    pub post_status: PostStatus,
    pub post_format: String,
    pub imported: bool,
    pub import_approved: bool,
    pub password: String,
    pub meta_description: String,
    pub twitter_description: String,
    pub pinned: bool,
}